services:
    notification.manager.log:
        class: PlanMyLife\NotificationBundle\Manager\LogNotificationManager
        arguments:
            - "@logger"
    notification.manager.flash_bag:
        class: PlanMyLife\NotificationBundle\Manager\FlashBagNotificationManager
        arguments:
            - "@session"
    notification.manager.debug:
        class: PlanMyLife\NotificationBundle\Manager\DebugNotificationManager
        arguments:
            - "%kernel.environment%"
    notification.manager.slack:
        class: PlanMyLife\NotificationBundle\Manager\SlackNotificationManager
        arguments:
            - "@cl_slack.api_client"
